import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { useEffect } from "react";
import { Providers } from "./providers";
import { GlobalProvider } from "@/context/useGoble";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Providers>
            <Header />
            <div className="container px-6 py-4 mx-auto w-full h-auto ">
              {children}
            </div>
            <Footer />
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  );
}
